### PR TITLE
Upgrade version to 1.2.0

### PR DESCRIPTION
**Pull request by supl**
This PR upgrades the Java module scalar-admin to 1.2.0 for the new gRPC service `checkPaused`.

After this PR is merged and the module is released, we can upgrade the dependencies in scalar and scalrdb and update the server-side codes.

### CODE REVIEW

**Review by brfrn169 — APPROVED** [review]
Regarding the change in this PR, LGTM! Thank you!

Do you know the problem where the `scalar-admin-x.x.x.jar` is not released for some reason from `1.1.0`?
https://repo1.maven.org/maven2/com/scalar-labs/scalar-admin/1.1.0/

`scalar-admin-1.1.0.jar` should be put in the above, but it isn't. It looks like it's related to the docker Gradle plugin. After removing the plugin, it seems like we can release the jar. I'm not sure of a proper solution for now. We need to fix this issue before releasing `1.2.0`.

**Review by feeblefakie — APPROVED** [review]
LGTM!

**Comment by supl** [comment]
> Regarding the change in this PR, LGTM! Thank you!
> 
> Do you know the problem where the `scalar-admin-x.x.x.jar` is not released for some reason from `1.1.0`? https://repo1.maven.org/maven2/com/scalar-labs/scalar-admin/1.1.0/
> 
> `scalar-admin-1.1.0.jar` should be put in the above, but it isn't. It looks like it's related to the docker Gradle plugin. After removing the plugin, it seems like we can release the jar. I'm not sure of a proper solution for now. We need to fix this issue before releasing `1.2.0`.

Thank you for your advice.
Let me investigate the issue.

**Comment by supl** [comment]
> Regarding the change in this PR, LGTM! Thank you!
> 
> Do you know the problem where the `scalar-admin-x.x.x.jar` is not released for some reason from `1.1.0`? https://repo1.maven.org/maven2/com/scalar-labs/scalar-admin/1.1.0/
> 
> `scalar-admin-1.1.0.jar` should be put in the above, but it isn't. It looks like it's related to the docker Gradle plugin. After removing the plugin, it seems like we can release the jar. I'm not sure of a proper solution for now. We need to fix this issue before releasing `1.2.0`.

It seems that the Gradle docker task (created by docker plugin) fails because it cannot find the scalar-admin.tar file when running the [Dockerfile](https://github.com/scalar-labs/scalar-admin/blob/main/java/Dockerfile#L8).

I created #13 to fix it.

**Pull request merged**
