### PR TITLE
Fix the `maven-publish` workflow

### PR DESCRIPTION
**Pull request by supl**
This PR fixes(?) an issue that I might indent command lines incorrectly.

I am not sure about the behavior of indenting them one more level so better to make them at the same level.

### CODE REVIEW

**Review by feeblefakie — COMMENTED** [review]
Just formatting?
Or, the previous way failed?

**Comment by supl** [comment]
> Just formatting?
> Or, the previous way failed?

@feeblefakie 
The previous way failed.
https://github.com/scalar-labs/scalar-admin/actions/runs/3993616006/jobs/6850493792#step:4:1

I am not sure if it's problem from indenting so I make it the same as the scalar repository.

**Comment by feeblefakie** [comment]
@supl Secrets like `SIGNING_SECRET_KEY_RING` are configured?

**Comment by supl** [comment]
> @supl Secrets like `SIGNING_SECRET_KEY_RING` are configured?

@feeblefakie 

Ah, sorry, I thought they are set as organization-scoped secrets.

I just add mine to the repository secrets.

**Review by feeblefakie — APPROVED** [review]
LGTM! Thank you!

**Pull request merged**
